<Welcome_Frame>
    
    canvas.before:

        Color:
            rgba : app.background_color
        
        Rectangle:
            pos  : self.pos
            size : self.size
    
    AnchorLayout:
        
        anchor_x : "center"
        anchor_y : "center"

        Label:
            text : app.display_text
            color : app.text_color
            font_size : self.width * 0.15
            


<Main_Page_Frame>

    canvas.before:
        
        Color:
            rgba : app.background_color

        Rectangle:
            pos  : self.pos
            size : self.size

    FloatLayout:

        Label:
            text : app.time
            color : app.text_color
            font_size : self.width * 0.15
            size_hint : (0.5,0.2)
            pos_hint : {'x' : 0.35, 'y' : 0.7}            
        

        Label:
            text : "\n\n"+app.date
            color : app.text_color
            font_size : self.width * 0.08
            size_hint : (0.5,0.2)
            pos_hint : {'x' : 0.35, 'y' : 0.7} 



        Button:
            text : "Settings"
            color : app.button_color
            font_size : self.width * 0.12
            size_hint : (0.2,0.15)
            pos_hint : {'x' : 0.1, 'y' : 0.7}
            on_press:
                root.manager.current = 'Settings_Color'


        Button:
            text : "File Sorter"
            color : app.button_color
            font_size : self.width * 0.12
            size_hint : (0.2,0.15)
            pos_hint : {'x' : 0.1, 'y' : 0.5}
            on_press:
                root.manager.current = 'File_Sorter'


        Button:
            text : "Hand Gesture"
            color : app.button_color
            font_size : self.width * 0.12
            size_hint : (0.2,0.15)
            pos_hint : {'x' : 0.1, 'y' : 0.3}
            on_press:
                root.manager.current = 'Hand_Gesture'
            

        Button:
            text : "Tab Organiser"
            color : app.button_color
            font_size : self.width * 0.12
            size_hint : (0.2,0.15)
            pos_hint : {'x' : 0.1, 'y' : 0.1}
            on_press:
                root.manager.current = 'Tab_Organizer'



<File_Sorter_Frame>
    
    canvas.before:
        
        Color:
            rgba : app.background_color

        Rectangle:
            pos  : self.pos
            size : self.size

    FloatLayout:
    
        Button:
            text : "Home"
            color : app.button_color
            font_size : self.width * 0.12
            size_hint : (0.1,0.075)
            pos_hint : {'x' : 0.1, 'y' : 0.8}
            on_press:
                root.manager.current = 'Main_Page'
                

        Button:
            text: 'choose folder'
            color : app.button_color
            font_size : self.width * 0.12
            size_hint : (0.1,0.075)
            pos_hint : {'x' : 0.1, 'y' : 0.6}
            on_press: root.select_source_folder()


        TextInput:
            text : root.source_path
            color : app.text_color
            hint_text : "Enter your Source path path here"
            font_size : self.width * 0.05
            size_hint : (0.4 , 0.05)
            pos_hint : {'x' : 0.2, 'y' : 0.6}     
            multiline : False
            on_text : root.selected_source([self.text])


        Button:
            text: 'choose folder'
            color : app.button_color
            font_size : self.width * 0.12
            size_hint : (0.1,0.075)
            pos_hint : {'x' : 0.1, 'y' : 0.5}
            on_press: root.select_destination_folder()


        TextInput:
            text : root.destination_path
            hint_text : "Enter your destination path path here"
            color : app.text_color
            font_size : self.width * 0.05
            size_hint : (0.4 , 0.05)
            pos_hint : {'x' : 0.2, 'y' : 0.5}     
            multiline : False
            on_text : root.selected_destination([self.text])


        Button:
            text : 'Copy Files'
            color : app.button_color
            font_size : self.width * 0.12
            size_hint : (0.1,0.075)
            pos_hint : {'x' : 0.8, 'y' : 0.3}
            on_press : root.execution_validation()


        Spinner:
            text : 'Sort types'
            color : app.button_color
            font_size : self.width * 0.12
            values : ('Sort by \ncreation date', 'Sort by \nlast edit', 'YYYYMMDD', 'YYYYDDMM', 'Sort by \nfile type')
            size_hint : (0.1,0.075)
            pos_hint : {'x' : 0.1, 'y' : 0.4}
            on_text: root.on_spinner_select(self.text)



<Popup_Frame>

    size_hint: (0.75, 0.35)

    FloatLayout:
        Label:
            text : root.text
            color : (0.9,0.9,0.9,1)
            font_size : self.width * 0.03
            size_hint : (0.8,0.4)
            pos_hint : {'center_x' : 0.5, 'center_y' : 0.7}  

        Button: 
            disabled : not root.confirmation
            opacity: 1 if not self.disabled else 0
            text : "Confirm"
            color : (0.9,0.9,0.9,1)
            font_size : self.width * 0.08
            size_hint : (0.4,0.2)
            pos_hint : {'center_x' : 0.75, 'center_y' : 0.3}
            on_press : root.confirmation_action()

        Button:
            text : "Close"
            color : (0.9,0.9,0.9,1)
            font_size : self.width * 0.08
            size_hint : (0.4,0.2)
            pos_hint : {'center_x' : 0.25, 'center_y' : 0.3} if root.confirmation else {'center_x' : 0.5, 'center_y' : 0.3}
            on_press : root.dismiss()



<Hand_Gesture_Frame>

    canvas.before:
        
        Color:
            rgba : app.background_color

        Rectangle:
            pos  : self.pos
            size : self.size

    FloatLayout:
    
        Button:
            text : "Home"
            color : app.button_color
            font_size : self.width * 0.12
            size_hint : (0.1,0.075)
            pos_hint : {'x' : 0.1, 'y' : 0.8}
            on_press:

                root.manager.current = 'Main_Page'

        Button:
            text : "Toggle"
            color : (1,0,0,1) if root.toggle else (0,1,0,1)
            font_size : self.width * 0.12
            size_hint : (0.1,0.075)
            pos_hint : {'x' : 0.1, 'y' : 0.65}
            on_press: 
                root.toggle = not root.toggle
                root.start_stop_hand_gesture()

        Button:
            text : "Debug Display"
            color : (1,0,0,1) if root.display else (0,1,0,1)
            font_size : self.width * 0.12
            size_hint : (0.1,0.075)
            pos_hint : {'x' : 0.1, 'y' : 0.55}
            on_press:
                root.display = not root.display




        Spinner:
            text : root.point_left
            color : app.button_color
            font_size : self.width * 0.12
            values : ('Last Song', 'Last Tab')
            size_hint : (0.15,0.1)
            pos_hint : {'x' : 0.2, 'y' : 0.4}
            on_text: root.update_pointer_option(0, self.text)

        Spinner:
            text : root.point_right
            color : app.button_color
            font_size : self.width * 0.12
            values : ('Next Song', 'Next Tab')
            size_hint : (0.15,0.1)
            pos_hint : {'x' : 0.6, 'y' : 0.4}
            on_text: root.update_pointer_option(1, self.text)

        Spinner:
            text : root.point_top
            color : app.button_color
            font_size : self.width * 0.12
            values : ('Increase Volume', 'Apps Overview')
            size_hint : (0.15,0.1)
            pos_hint : {'x' : 0.4, 'y' : 0.6}
            on_text: root.update_pointer_option(2, self.text)

        Spinner:
            text : root.point_bottom
            color : app.button_color
            font_size : self.width * 0.12
            values : ('Decrease Volume', 'Clear Screen')
            size_hint : (0.15,0.1)
            pos_hint : {'x' : 0.4, 'y' : 0.2}
            on_text: root.update_pointer_option(3, self.text)

       

<Tab_Organizer_Frame>

    canvas.before:

        Color:
            rgba : app.background_color

        Rectangle:
            pos  : self.pos
            size : self.size

    FloatLayout:
    
        Button:
            text : "Home"
            color : app.button_color
            font_size : self.width * 0.12
            size_hint : (0.1,0.075)
            pos_hint : {'x' : 0.1, 'y' : 0.8}
            on_press:
                root.manager.current = 'Main_Page'

        Button:
            text : "Desktop 1"
            color : app.button_color
            font_size : self.width * 0.12
            size_hint : (0.1,0.075)
            pos_hint : {'x' : 0.025, 'y' : 0.5}
            on_press:
                root.switch_desktop(0)
            
        Button:
            text : "Desktop 2"
            color : app.button_color
            font_size : self.width * 0.12
            size_hint : (0.1,0.075)
            pos_hint : {'x' : 0.275, 'y' : 0.5}
            on_press:
                root.switch_desktop(1)
        
        Button:
            text : "Desktop 3"
            color : app.button_color
            font_size : self.width * 0.12
            size_hint : (0.1,0.075)
            pos_hint : {'x' : 0.525, 'y' : 0.5}
            on_press:
                root.switch_desktop(2)

        Button:
            text : "Desktop 4"
            color : app.button_color
            font_size : self.width * 0.12
            size_hint : (0.1,0.075)
            pos_hint : {'x' : 0.775, 'y' : 0.5}
            on_press:
                root.switch_desktop(3)



<Setting_Shortcut_Frame>

    canvas.before:
        
        Color:
            rgba : app.background_color

        Rectangle:
            pos  : self.pos
            size : self.size
    

    FloatLayout:
    
        Button:
            text : "Colors"
            color : app.button_color
            font_size : self.width * 0.12
            size_hint : (0.1,0.075)
            pos_hint : {'x' : 0.3, 'y' : 0.8}
            on_press:
                root.manager.current = 'Settings_Color'
                 

        Button:
            text : "Home"
            color : app.button_color
            font_size : self.width * 0.12
            size_hint : (0.1,0.075)
            pos_hint : {'x' : 0.1, 'y' : 0.8}
            on_press:
                root.manager.current = 'Main_Page'

        Label:
            text : "Overlay Shortcut"
            color : app.text_color
            font_size : self.width * 0.08
            size_hint : (0.4,0.2)
            pos_hint : {'x' : -0.03, 'y' : 0.61}

        TextInput:
            text : app.overlay_shortcut
            color : app.text_color
            hint_text : "Enter Shortcut keybind here"
            font_size : self.width * 0.05
            size_hint : (0.4 , 0.05)
            pos_hint : {'x' : 0.05, 'y' : 0.6}  
            multiline : False
            on_text : root.keybind = self.text





        TextInput:
            text : app.shortcut_names[0]
            color : app.text_color
            hint_text : "Enter Shortcut Name here"
            font_size : self.width * 0.1
            size_hint : (0.22,0.065)
            multiline : False
            pos_hint : {'x' : 0.025, 'y' : 0.5}
            on_text : root.update_name(0,self.text)
            

        Spinner:
            text : root.spinner_current_1_1
            color : app.button_color
            font_size : self.width * 0.1
            values : ('start_application', 'switch_desktop', 'move_window_to_desktop', 'switch_to_app')
            size_hint : (0.22,0.065)
            pos_hint : {'x' : 0.025, 'y' : 0.4}
            on_text: root.spiiner_type_select(0, self.text)

        TextInput:
            text : root.spinner_current_1_2
            color : app.button_color
            hint_text : "Enter Application Name Here"
            font_size : self.width * 0.12
            size_hint : (0.22,0.065)
            multiline : False
            pos_hint : {'x' : 0.025, 'y' : 0.32}
            on_text : root.update_parameter(0,self.text,'start_application')
            disabled : not root.buttons[0][0]
            opacity: 0 if self.disabled else 1

        Spinner:
            text : root.spinner_current_1_3
            color : app.button_color
            font_size : self.width * 0.12
            values : ('Desktop 1', 'Desktop 2', 'Desktop 3', 'Desktop 4')
            size_hint : (0.22,0.065)
            pos_hint : {'x' : 0.025, 'y' : 0.24}
            on_text : root.update_parameter(0,self.text,'switch_desktop')
            disabled : not root.buttons[0][1] 
            opacity: 0 if self.disabled else 1

        Spinner:
            text : root.spinner_current_1_4
            color : app.button_color
            font_size : self.width * 0.12
            values : ('Desktop 1', 'Desktop 2', 'Desktop 3', 'Desktop 4')
            size_hint : (0.22,0.065)
            pos_hint : {'x' : 0.025, 'y' : 0.16}
            on_text : root.update_parameter(0,self.text,'move_window_to_desktop')
            disabled : not root.buttons[0][2] 
            opacity: 0 if self.disabled else 1

        Spinner:
            text : root.spinner_current_1_5
            color : app.button_color
            font_size : self.width * 0.12
            values : ('Main_Page', 'File_Sorter', 'Hand_Gesture', 'Tab_Organizer', 'Settings_Color', 'Settings_Shortcut')
            size_hint : (0.22,0.065)
            pos_hint : {'x' : 0.025, 'y' : 0.08}
            on_text : root.update_parameter(0,self.text,'switch_to_app')
            disabled : not root.buttons[0][3] 
            opacity: 0 if self.disabled else 1





        
        TextInput:
            text : app.shortcut_names[1]
            color : app.text_color
            hint_text : "Enter Shortcut Name here"
            font_size : self.width * 0.1
            size_hint : (0.22,0.065)
            multiline : False
            pos_hint : {'x' : 0.275, 'y' : 0.5}
            on_text : root.update_name(1,self.text)

        Spinner:
            text : root.spinner_current_2_1
            color : app.button_color
            font_size : self.width * 0.1
            values : ('start_application', 'switch_desktop', 'move_window_to_desktop', 'switch_to_app')
            size_hint : (0.22,0.065)
            pos_hint : {'x' : 0.275, 'y' : 0.4}
            on_text: root.spiiner_type_select(1, self.text)

        TextInput:
            text : root.spinner_current_2_2
            color : app.button_color
            hint_text : "Enter Application Name Here"
            font_size : self.width * 0.12
            size_hint : (0.22,0.065)
            multiline : False
            pos_hint : {'x' : 0.275, 'y' : 0.32}
            on_text : root.update_parameter(1,self.text,'start_application')
            disabled : not root.buttons[1][0]
            opacity: 0 if self.disabled else 1

        Spinner:
            text : root.spinner_current_2_3
            color : app.button_color
            font_size : self.width * 0.12
            values : ('Desktop 1', 'Desktop 2', 'Desktop 3', 'Desktop 4')
            size_hint : (0.22,0.065)
            pos_hint : {'x' : 0.275, 'y' : 0.24}
            on_text : root.update_parameter(1,self.text,'switch_desktop')
            disabled : not root.buttons[1][1] 
            opacity: 0 if self.disabled else 1

        Spinner:
            text : root.spinner_current_2_4
            color : app.button_color
            font_size : self.width * 0.12
            values : ('Desktop 1', 'Desktop 2', 'Desktop 3', 'Desktop 4')
            size_hint : (0.22,0.065)
            pos_hint : {'x' : 0.275, 'y' : 0.16}
            on_text : root.update_parameter(1,self.text,'move_window_to_desktop')
            disabled : not root.buttons[1][2] 
            opacity: 0 if self.disabled else 1

        Spinner:
            text : root.spinner_current_2_5
            color : app.button_color
            font_size : self.width * 0.12
            values : ('Main_Page', 'File_Sorter', 'Hand_Gesture', 'Tab_Organizer', 'Settings_Color', 'Settings_Shortcut')
            size_hint : (0.22,0.065)
            pos_hint : {'x' : 0.275, 'y' : 0.08}
            on_text : root.update_parameter(1,self.text,'switch_to_app')
            disabled : not root.buttons[1][3] 
            opacity: 0 if self.disabled else 1
        
        
        


        
        TextInput:
            text : app.shortcut_names[2]
            color : app.text_color
            hint_text : "Enter Shortcut Name here"
            font_size : self.width * 0.1
            size_hint : (0.22,0.065)
            multiline : False
            pos_hint : {'x' : 0.525, 'y' : 0.5}
            on_text : root.update_name(2,self.text)

        Spinner:
            text : root.spinner_current_3_1
            color : app.button_color
            font_size : self.width * 0.1
            values : ('start_application', 'switch_desktop', 'move_window_to_desktop', 'switch_to_app')
            size_hint : (0.22,0.065)
            pos_hint : {'x' : 0.525, 'y' : 0.4}
            on_text: root.spiiner_type_select(2, self.text)

        TextInput:
            text : root.spinner_current_3_2
            color : app.button_color
            hint_text : "Enter Application Name Here"
            font_size : self.width * 0.12
            size_hint : (0.22,0.065)
            multiline : False
            pos_hint : {'x' : 0.525, 'y' : 0.32}
            on_text : root.update_parameter(2,self.text,'start_application')
            disabled : not root.buttons[2][0]
            opacity: 0 if self.disabled else 1

        Spinner:
            text : root.spinner_current_3_3
            color : app.button_color
            font_size : self.width * 0.12
            values : ('Desktop 1', 'Desktop 2', 'Desktop 3', 'Desktop 4')
            size_hint : (0.22,0.065)
            pos_hint : {'x' : 0.525, 'y' : 0.24}
            on_text : root.update_parameter(2,self.text,'switch_desktop')
            disabled : not root.buttons[2][1] 
            opacity: 0 if self.disabled else 1

        Spinner:
            text : root.spinner_current_3_4
            color : app.button_color
            font_size : self.width * 0.12
            values : ('Desktop 1', 'Desktop 2', 'Desktop 3', 'Desktop 4')
            size_hint : (0.22,0.065)
            pos_hint : {'x' : 0.525, 'y' : 0.16}
            on_text : root.update_parameter(2,self.text,'move_window_to_desktop')
            disabled : not root.buttons[2][2] 
            opacity: 0 if self.disabled else 1

        Spinner:
            text : root.spinner_current_3_5
            color : app.button_color
            font_size : self.width * 0.12
            values : ('Main_Page', 'File_Sorter', 'Hand_Gesture', 'Tab_Organizer', 'Settings_Color', 'Settings_Shortcut')
            size_hint : (0.22,0.065)
            pos_hint : {'x' : 0.525, 'y' : 0.08}
            on_text : root.update_parameter(2,self.text,'switch_to_app')
            disabled : not root.buttons[2][3] 
            opacity: 0 if self.disabled else 1
        
        
        
        


        
        TextInput:
            text : app.shortcut_names[3]
            color : app.text_color
            hint_text : "Enter Shortcut Name here"
            font_size : self.width * 0.1
            size_hint : (0.22,0.065)
            multiline : False
            pos_hint : {'x' : 0.775, 'y' : 0.5}
            on_text : root.update_name(3,self.text)

        Spinner:
            text : root.spinner_current_4_1
            color : app.button_color
            font_size : self.width * 0.1
            values : ('start_application', 'switch_desktop', 'move_window_to_desktop', 'switch_to_app')
            size_hint : (0.22,0.065)
            pos_hint : {'x' : 0.775, 'y' : 0.4}
            on_text: root.spiiner_type_select(3, self.text)

        TextInput:
            text : root.spinner_current_4_2
            color : app.button_color
            hint_text : "Enter Application Name Here"
            font_size : self.width * 0.12
            size_hint : (0.22,0.065)
            multiline : False
            pos_hint : {'x' : 0.775, 'y' : 0.32}
            on_text : root.update_parameter(3,self.text,'start_application')
            disabled : not root.buttons[3][0]
            opacity: 0 if self.disabled else 1

        Spinner:
            text : root.spinner_current_4_3
            color : app.button_color
            font_size : self.width * 0.12
            values : ('Desktop 1', 'Desktop 2', 'Desktop 3', 'Desktop 4')
            size_hint : (0.22,0.065)
            pos_hint : {'x' : 0.775, 'y' : 0.24}
            on_text : root.update_parameter(3,self.text,'switch_desktop')
            disabled : not root.buttons[3][1] 
            opacity: 0 if self.disabled else 1

        Spinner:
            text : root.spinner_current_4_4
            color : app.button_color
            font_size : self.width * 0.12
            values : ('Desktop 1', 'Desktop 2', 'Desktop 3', 'Desktop 4')
            size_hint : (0.22,0.065)
            pos_hint : {'x' : 0.775, 'y' : 0.16}
            on_text : root.update_parameter(3,self.text,'move_window_to_desktop')
            disabled : not root.buttons[3][2] 
            opacity: 0 if self.disabled else 1

        Spinner:
            text : root.spinner_current_4_5
            color : app.button_color
            font_size : self.width * 0.12
            values : ('Main_Page', 'File_Sorter', 'Hand_Gesture', 'Tab_Organizer', 'Settings_Color', 'Settings_Shortcut')
            size_hint : (0.22,0.065)
            pos_hint : {'x' : 0.775, 'y' : 0.08}
            on_text : root.update_parameter(3,self.text,'switch_to_app')
            disabled : not root.buttons[3][3] 
            opacity: 0 if self.disabled else 1

        Button:
            text : "Confirm"
            color : app.button_color
            font_size : self.width * 0.12
            size_hint : (0.1,0.075)
            pos_hint : {'x' : 0.8, 'y' : 0.8}
            on_press : root.confirm()



<Setting_Color_Frame>

    canvas.before:
        
        Color:
            rgba : app.background_color

        Rectangle:
            pos  : self.pos
            size : self.size
    

    FloatLayout:
    
        Button:
            text : "Shortcuts"
            color : app.button_color
            font_size : self.width * 0.12
            size_hint : (0.1,0.075)
            pos_hint : {'x' : 0.3, 'y' : 0.8}
            on_press:

                root.manager.current = 'Settings_Shortcut'

        Button:
            text : "Home"
            color : app.button_color
            font_size : self.width * 0.12
            size_hint : (0.1,0.075)
            pos_hint : {'x' : 0.1, 'y' : 0.8}
            on_press:

                root.manager.current = 'Main_Page'
        

        Label:
            text : "Text Color"
            color : app.text_color
            font_size : self.width * 0.08
            size_hint : (0.4,0.2)
            pos_hint : {'x' : -0.06, 'y' : 0.5}

        Slider:
            value_track_color : (1,0,0,1)
            value_track : True
            orientation : "horizontal"
            size_hint : (0.3,0.075)
            pos_hint : {'x' : 0.05, 'y' : 0.5}
            min : 0
            max : 1
            value : app.text_color[0]
            on_touch_move : root.set_text_theme(0, self.value)

        Slider:
            value_track_color : (0,1,0,1)
            value_track : True
            orientation : "horizontal"
            size_hint : (0.3,0.075)
            pos_hint : {'x' : 0.05, 'y' : 0.4}
            min : 0
            max : 1
            value : app.text_color[1]
            on_touch_move : root.set_text_theme(1, self.value)

        Slider:
            value_track_color : (0,0,1,1)
            value_track : True
            orientation : "horizontal"
            size_hint : (0.3,0.075)
            pos_hint : {'x' : 0.05, 'y' : 0.3}
            min : 0
            max : 1
            value : app.text_color[2]
            on_touch_move : root.set_text_theme(2, self.value)


        Label:
            text : "Background Color"
            color : app.text_color
            font_size : self.width * 0.08
            size_hint : (0.4,0.2)
            pos_hint : {'x' : 0.29, 'y' : 0.5}

        Slider:
            value_track_color : (1,0,0,1)
            value_track : True
            orientation : "horizontal"
            size_hint : (0.3,0.075)
            pos_hint : {'x' : 0.35, 'y' : 0.5}
            min : 0
            max : 1
            value : app.background_color[0]
            on_touch_move : root.set_background_theme(0, self.value)

        Slider:
            value_track_color : (0,1,0,1)
            value_track : True
            orientation : "horizontal"
            size_hint : (0.3,0.075)
            pos_hint : {'x' : 0.35, 'y' : 0.4}
            min : 0
            max : 1
            value : app.background_color[1]
            on_touch_move : root.set_background_theme(1, self.value)

        Slider:
            value_track_color : (0,0,1,1)
            value_track : True
            orientation : "horizontal"
            size_hint : (0.3,0.075)
            pos_hint : {'x' : 0.35, 'y' : 0.3}
            min : 0
            max : 1
            value : app.background_color[2]
            on_touch_move : root.set_background_theme(2, self.value)


        Label:
            text : "Button Color"
            color : app.text_color
            font_size : self.width * 0.08
            size_hint : (0.4,0.2)
            pos_hint : {'x' : 0.55, 'y' : 0.5}

        Slider:
            value_track_color : (1,0,0,1)
            value_track : True
            orientation : "horizontal"
            size_hint : (0.3,0.075)
            pos_hint : {'x' : 0.65, 'y' : 0.5}
            min : 0
            max : 1
            value : app.button_color[0]
            on_touch_move : root.set_button_theme(0, self.value)

        Slider:
            value_track_color : (0,1,0,1)
            value_track : True
            orientation : "horizontal"
            size_hint : (0.3,0.075)
            pos_hint : {'x' : 0.65, 'y' : 0.4}
            min : 0
            max : 1
            value : app.button_color[1]
            on_touch_move : root.set_button_theme(1, self.value)



        Slider:
            value_track_color : (0,0,1,1)
            value_track : True
            orientation : "horizontal"
            size_hint : (0.3,0.075)
            pos_hint : {'x' : 0.65, 'y' : 0.3}
            min : 0
            max : 1
            value : app.button_color[2]
            on_touch_move : root.set_button_theme(2, self.value)


        Button:
            text : "Reset"
            color : app.button_color
            font_size : self.width * 0.12
            size_hint : (0.1,0.075) 
            pos_hint : {'x' : 0.8, 'y' : 0.8}
            on_press : 
                root.set_text_theme(0, 0)
                root.set_text_theme(1, 0)
                root.set_text_theme(2, 0)
                root.set_background_theme(0, 1)
                root.set_background_theme(1, 1)
                root.set_background_theme(2, 1)
                root.set_button_theme(0, 1)
                root.set_button_theme(1, 1)
                root.set_button_theme(2, 1)



<Overlay_Frame>
    
    canvas.before:

        Color:
            rgba : app.background_color

        Rectangle:
            pos  : self.pos
            size : self.size

    Button:
        text : app.shortcut_names[0]
        color : app.button_color
        font_size : self.width * 0.12
        size_hint : (0.3,0.2)
        pos_hint : {'x' : 0.35, 'y' : 0.6}
        on_press:
            root.button_function(1)

    Button:
        text : app.shortcut_names[1]
        color : app.button_color
        font_size : self.width * 0.12
        size_hint : (0.3,0.2)
        pos_hint : {'x' : 0.6, 'y' : 0.4}
        on_press:
            root.button_function(2)

    Button:
        text : app.shortcut_names[2]
        color : app.button_color
        font_size : self.width * 0.12
        size_hint : (0.3,0.2)
        pos_hint : {'x' : 0.35, 'y' : 0.2}
        on_press:
            root.button_function(3)

    Button:
        text : app.shortcut_names[3]
        color : app.button_color
        font_size : self.width * 0.12
        size_hint : (0.3,0.2)
        pos_hint : {'x' : 0.1, 'y' : 0.4}
        on_press:
            root.button_function(4)
